[versions]

agp = "8.12.3"
caupain = "1.8.1"
dokka = "2.1.0"
kotlin = "2.3.10"
maven-publish = "0.36.0"
kotlinx-coroutines = "1.10.2"
kotlinx-binary-validator = "0.18.1"
kotlinx-io = "0.9.0"
junit-jupiter = "6.0.3"

[libraries]

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
# IO
kotlinx-io-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlinx-io" }
# JUnit
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }

[plugins]

android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
caupain = { id = "com.deezer.caupain", version.ref = "caupain" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"  }
kotlinx-binary-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binary-validator" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }